name: Go CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go_final_project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Export PORT
        run: echo "PORT=7540" >> $GITHUB_ENV

      - name: Start API server
        run: |
          go run main.go &            
          for i in {1..10}; do
            curl --silent http://localhost:7540/ && break
            sleep 1
          done

      - name: Run tests
        run: go test ./... -v
